language: python
python:
  - "3.6"
install:
  - make init
script:
  - sed -i "s/sed -i ''/sed -i/g" Makefile # Make Makefile works on GNU
  - make run
  - echo "fullstackpython.qiwihui.com" > generated/updated_site/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: generated/updated_site/
  on:
    branch: zh-CN